version: '3.9'
services:
  app:
    build:
      context: ./app
    environment:
      VITE_API_URL: 'http://api:4000'
      DETECTOR_API_URL: 'http://stream:8080'
    ports:
      - "3000:3000"
  api:
    build:
      context: ./api
    env_file:
      - secret.env
    ports:
      - "4000:4000"
  stream:
    build:
      context: ./stream
    ports:
      - "8080:8080"
